### ISSUE TITLE
Issue occurs in final month

### ISSUE THREAD

**Issue by Akery** [staticlibs/ccronexpr#36] opened 2022-12-16 09:54 UTC
Issue occurs in final month

Example:
Expression: " 0 0 17 16 * * "
![image](https://user-images.githubusercontent.com/12009446/208072107-589840c1-ebda-4a59-9f88-51b3ce0d9b61.png)

Example correct result:
Expression: " 0 0 17 16 * * "
Current time: 2023-12-16 17:00:00

**Comment by exander77** [comment] 2023-09-08 20:11
I cannot reproduce.

**Comment by staticlibs** [comment] 2023-09-10 12:19
This project is no longer maintained, see its updated and extended fork in [exander77/supertinycron](https://github.com/exander77/supertinycron) repo, closing the issue to archive the repo.

**Closed by staticlibs** 2023-09-10 12:19 UTC
